---
title: "Post Concert Report"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
#######################################################################
# User input is required to run this code:

# Lookup Number - Run the code up through pre-load. This will generate 
#   the unique perf data frame, in here, you can see what number 
#   aligns with the perf date of the concert. Enter that number for the 
#   user input. Use the LAST perf date in the series. Then execute/knit 
#   the entire rmd file.

# User must also update the concert date of FIRST concert in series (assuming
#   the series dates don't skip any dates. If they do, date must be entered
#   manually instead of using the +1 method).

# This may not include enough tabs for each concert in the series or may 
#   include too many. Copy paste additional date tabs if necessary or delete
#   them out if there are too many included.

###################### LIBS ###########################
library(lubridate)
library(tidyverse)
library(scales)
library(knitr)
library(kableExtra)

#######################################################
###################### USER INPUT #####################
#######################################################
# Concert number is used for audience flow, use last concert in series
# If fiscal year changes, review code as there are some breaks that will occur
concert_number_lookup <- 40
concert_type <- 'clx'
this_fy <- 2019
date_of_first_concert <- as.Date('2019-04-11')
name_of_series <- 'ASpaceOdyssey'

###################### PRE-LOAD #######################
LoadData <- function(){
  rbind(read.csv('/data/ticketing/Clx19.csv', header = TRUE, skip = 3),
        read.csv('/data/ticketing/Pops19.csv', header = TRUE, skip = 3),
        read.csv('/data/ticketing/Summer19.csv', header = TRUE, skip = 3)) %>%
    mutate(perf_dt = mdy_hms(perf_dt))
}
df_og <- LoadData()

UniquePerfDataframe <- function(dt){
  dt %>% 
    distinct(perf_dt) %>%
    arrange(perf_dt) %>%
    mutate(concert_number_lookup = c(1:53))
}
perf_dts_unique <- UniquePerfDataframe(df_og)

###################### FUNCTIONS ######################
##### Perf Summ #####

NewDf <- function(dt){
  dt %>%
    mutate(price_zone = substr(zone_desc, 1, 7),
           price_type_group = replace(price_type_group, price_type_group == "Flex", "Subscription"),
           price_type_group = replace(price_type_group, price_type_group == "Discount", "Single "),
           price_type_group = str_trim(price_type_group)) %>%
    filter(perf_dt > date_of_concert &
             perf_dt < date_of_concert + 1) %>%
    select(price_zone,price_type_group,paid_amt,attended) %>%
    mutate(row_count = 1)
}


SummarizeDf <- function(dt){
  dt %>%
    group_by(price_zone) %>%
    summarize(Seats = n(),
              SubSold = sum(row_count[price_type_group == 'Subscription']),
              SubAvg = mean(paid_amt[price_type_group == 'Subscription']),
              SubRev = sum(paid_amt[price_type_group == 'Subscription']),
              SglSold = sum(row_count[price_type_group == 'Single']),
              SglAvg = mean(paid_amt[price_type_group == 'Single']),
              SglRev = sum(paid_amt[price_type_group == 'Single']),
              TotSold = sum(row_count[price_type_group == 'Subscription' | 
                                                      price_type_group == 'Single']),
              PrcntSold = TotSold/Seats,
              TotRev = sum(SubRev,SglRev),
              TotComp = sum(row_count[price_type_group == 'Comp']),
              PrcntComp = TotComp/Seats,
              Att = sum(row_count[attended == 'Attended']),
              CompAtt = sum(row_count[attended == 'Attended' & 
                                                price_type_group == 'Comp'])/TotComp,
              SubAtt = sum(row_count[attended == 'Attended' & 
                                               price_type_group == 'Subscription'])/SubSold,
              SglAtt = sum(row_count[attended == 'Attended' & 
                                                  price_type_group == 'Single'])/SglSold,
              TotAtt = Att/sum(TotSold,TotComp)) %>%
    rename(Zone = price_zone)
}

BindFinalwTotalRow <- function(dt){
  x <- data.frame('Total',
             sum(dt$Seats),
             sum(dt$SubSold),
             sum(dt$SubRev)/sum(dt$SubSold),
             sum(dt$SubRev),
             sum(dt$SglSold),
             sum(dt$SglRev)/sum(dt$SglSold),
             sum(dt$SglRev),
             sum(dt$TotSold),
             sum(dt$TotSold)/sum(dt$Seats),
             sum(dt$TotRev),
             sum(dt$TotComp),
             sum(dt$TotComp)/sum(dt$Seats),
             sum(dt$Att),
             sum(dt$CompAtt*dt$TotComp)/sum(dt$TotComp),
             sum(dt$SubAtt*dt$SubSold)/sum(dt$SubSold),
             sum(dt$SglAtt*dt$SglSold)/sum(dt$SglSold),
             sum(dt$Att)/sum(dt$TotSold+dt$TotComp))
  colnames(x) <- names(dt)
  rbind(dt,x)
}

DataFormatting <- function(dt){
  dt %>%
    mutate(SubAvg = dollar(SubAvg),
         SubRev = dollar(SubRev),
         SglAvg = dollar(SglAvg),
         SglRev = dollar(SglRev),
         PrcntSold = percent(PrcntSold),
         TotRev = dollar(TotRev),
         PrcntComp = percent(PrcntComp),
         CompAtt = percent(CompAtt),
         SubAtt = percent(SubAtt),
         SglAtt = percent(SglAtt),
         TotAtt = percent(TotAtt))
}


#####################
##### Cust Flow #####
#####################


LookupValue <- function(dt,con_num=concert_number_lookup){
  df <- data.frame(con_num)
  names(df) <- c('concert_number_lookup')
  merge(df,dt)
}

SubDf <- function(dt){
  dt %>%
    filter(summary_cust_id > 0,
           price_type_group == 'Flex' |
             price_type_group == 'Subscription')
}

NewDf_CustFlow <- function(dt,value,dt_sub){
  dt %>%
    mutate(subscriber = summary_cust_id %in% dt_sub$summary_cust_id) %>%
    filter(summary_cust_id > 0, 
           perf_dt <= value$perf_dt[1],
           price_type_group != 'Comp',
           summary_cust_id != 2010347,
           subscriber == FALSE)
}

CreateUniquePerfSpread <- function(dt){
  dt %>%
    select(perf_dt, summary_cust_id) %>%
    distinct() %>%
    mutate(perf_counter = 1) %>%
    spread(key=perf_dt,
           value=perf_counter,
           fill=0)
}

AddTotalPerfs <- function(dt){
  dt %>%
    mutate(total_perfs = if(ncol(dt) > 2){
      rowSums(dt[,-1])
    } else {
      1
    })
}

AggTotalPerformances <- function(dt){
  dt %>%
    group_by(total_perfs) %>%
    tally() %>%
    rename(total_customers = n)
}

GeneratePlot <- function(dt){
  ggplot(data = dt, aes(x=total_perfs, y=total_customers, colors = 'black')) + 
    guides(fill=FALSE) + 
    geom_bar(stat='identity', fill='#166713', color = 'black') + 
    xlab('Concerts Attended') + 
    ylab('Total Customers') + 
    ggtitle('Concerts by Unique Customers (Non-Subs Only)') +
    scale_x_continuous(breaks = seq(1, max(dt$total_perfs), by = 1),
                       labels = seq(1, max(dt$total_perfs), by = 1),
                       limits = if(max(dt$total_perfs) >= 10){
                         c(0.5,max(dt$total_perfs)+0.5)
                       } else {
                         c(0.5,10)
                       }) + 
    theme_bw() + 
    theme(plot.title = element_text(hjust = 0.5, size = 16, face='bold'),
          axis.title = element_text(size = 14),
          panel.grid.minor = element_blank())
}

##########################################################################################
##########################################################################################
##########################################################################################
# AUDIENCE COMP
##########################################################################################
# import ticketing data
df_audience <- rbind(read.csv('/data/ticketing/Clx16.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Clx17.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Clx18.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Clx19.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Pops16.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Pops17.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Pops18.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Pops19.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Summer17.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Summer18.csv', header = TRUE, skip = 3),
                      read.csv('/data/ticketing/Summer19.csv', header = TRUE, skip = 3)) %>%
  mutate(perf_dt = mdy_hms(perf_dt))

summer16_df <- read.csv('/data/ticketing/summer16.csv', header = TRUE, skip = 3) %>%
  mutate(perf_dt = mdy_hm(perf_dt))

# Bind them together and remove summer16_df
df_audience <- rbind(df_audience,summer16_df)
rm(summer16_df)

df_audience <- df_audience[df_audience$summary_cust_id %in% names(which(table(df_audience$summary_cust_id) <= 500)),]

df <- df_audience %>%
  mutate(seat = paste(section,' ',row,'-',seat)) %>%
  select(summary_cust_id,season_desc,price_type_group,paid_amt,zone_desc,perf_dt,summary_cust_name,seat) %>%
  filter(summary_cust_id > 0,
         paid_amt > 5)

df <- df %>%  
  mutate(fy = ifelse(df$perf_dt < as.Date('2016-07-01'),
                     16,
                     ifelse(df$perf_dt < as.Date('2017-07-01'),
                            17,
                            ifelse(df$perf_dt < as.Date('2018-07-01'),
                                   18,19))))

# import donor data
df_donor <- read.csv('/data/donors/enhanced_fund_fy15-present.csv', header = TRUE) %>%
  filter(cont_fy == this_fy) %>%
  select(summary_cust_id,gift_plus_pledge) %>%
  group_by(summary_cust_id) %>%
  summarize(gift_plus_pledge = sum(gift_plus_pledge))

df_for_segmentation <- df %>%
  filter(fy == max(fy) |
           fy == max(fy)-1)

renew_df_creation <- function(df){
  df_renew <- df %>%
    filter(fy == max(fy)-1 |
             (fy == max(fy) & 
                perf_dt < concert_date)) %>%
    group_by(summary_cust_id) %>%
    summarize() %>%
    mutate(renew = 1)
}

return_df_creation <- function(df){
  df_return <- df %>%
    filter(fy == max(fy)-2 |
             fy == max(fy)-3) %>%
    group_by(summary_cust_id) %>%
    summarize() %>%
    mutate(return = 1)
}

subs_df_creation <- function(df){
  df_subscribers <- df %>%
    filter((fy == max(fy) & price_type_group == 'Subscription') |
             (fy == max(fy) & price_type_group == 'Flex')) %>%
    group_by(summary_cust_id) %>%
    summarize() %>%
    mutate(subscriber = 1)
}

seat_finder_df_creation <- function(df){
  df_seat_finder <- df %>%
    filter(perf_dt > concert_date &
             perf_dt < concert_date + 1) %>%
    select(summary_cust_id,summary_cust_name,seat)
}

this_concert_df_creation <- function(df){
  df_this_concert <- df %>%
    filter(perf_dt > concert_date & 
             perf_dt < concert_date + 1) %>%
    group_by(summary_cust_id) %>%
    summarize()
}

aggregate_df_creation <- function(df_for_segmentation){
  aggregate_df <- if(concert_type == 'clx'){
    df_for_segmentation %>%
      filter(season_desc == 'PS 17-18 Classics' |
               season_desc == 'PS 18-19 Classics') %>%
      group_by(summary_cust_id) %>%
      summarize(freq = n(),
                avg_paid_amt = mean(paid_amt),
                tot_paid_amt = sum(paid_amt))
  } else if (concert_type == 'pop'){
    df_for_segmentation %>%
      filter(season_desc == 'PS 17-18 Pops' |
               season_desc == 'PS 18-19 Pops') %>%
      group_by(summary_cust_id) %>%
      summarize(freq = n(),
                avg_paid_amt = mean(paid_amt),
                tot_paid_amt = sum(paid_amt))
  } else {
    df_for_segmentation %>%
      group_by(summary_cust_id) %>%
      summarize(freq = n(),
                avg_paid_amt = mean(paid_amt),
                tot_paid_amt = sum(paid_amt))
  }
}

addSegments <- function(dataset, 
                        ticket_price_avg, 
                        ticket_price_upper,
                        ticket_price_lower,
                        frequency_avg,
                        frequency_upper,
                        frequency_lower) {
  ifelse(dataset$avg_paid_amt > ticket_price_avg &
           dataset$freq > frequency_upper,
         'Aficionado',
         ifelse(dataset$avg_paid_amt < ticket_price_avg & 
                  dataset$freq > frequency_avg,
                'Committed low-budget',
                ifelse(dataset$avg_paid_amt < ticket_price_upper &
                         dataset$freq < frequency_avg &
                         dataset$freq > frequency_lower,
                       'Evolving concert-goer',
                       ifelse(dataset$avg_paid_amt > ticket_price_avg & 
                                dataset$freq < frequency_lower,
                              'High-value prospect',
                              ifelse(dataset$avg_paid_amt < ticket_price_avg &
                                       dataset$freq < frequency_lower,
                                     'One-timer', 'High-value regular')))))
}

plot_classification <- function(dt=df_this_concert){
  ggplot(data = dt %>%
           group_by(classification) %>%
           summarize(count = n()), 
         aes(x=classification, y=count, fill = classification)) + 
    guides(fill=FALSE) + 
    geom_bar(stat='identity', color = 'black') +
    theme(axis.title = element_blank())
}

plot_type <- function(dt=df_this_concert){
  ggplot(data = dt %>%
           mutate(subscriber = ifelse(subscriber == 1,'Subscription','Single')) %>%
           group_by(subscriber) %>%
           summarize(count = n()), 
         aes(x=subscriber, y=count, fill=subscriber)) + 
    guides(fill=FALSE) +
    geom_bar(stat='identity', color = 'black') +
    coord_flip() +
    theme(axis.title = element_blank())
}

plot_segment <- function(dt=df_this_concert){
  ggplot(data = dt %>%
           group_by(segment) %>%
           summarize(count = n()), 
         aes(x=segment, y=count, fill=segment)) + 
    guides(fill=FALSE) +
    geom_bar(stat='identity', color = 'black') +
    coord_flip() +
    theme(axis.title = element_blank())
}

plot_donor_group <- function(dt=df_this_concert){
  ggplot(data = dt %>%
           group_by(donor_group) %>%
           summarize(count = n()), 
         aes(x=donor_group, y=count, fill=donor_group)) + 
    guides(fill=FALSE) +
    geom_bar(stat='identity', color = 'black') +
    theme(axis.title = element_blank())
}


```

Cover
=========================================================================
Row
----------------------------
### `r paste(name_of_series)`

#### Report Instructions:

  1. Below describes each report included in this post-concert, performance application.
  2. Click through the pages across the top to see the reports included.


***

#### Report Descriptions

* The pages named as a date displays a variety of information regarding the performance and the audience composition on the given performance date. The included information details:  
    + Revenue Summary - displays all seats sold and revenue information by price zone.
    + Comp Data - Displays information regarding complimentary (free) tickets.
    + Attendence Data - Displays information regarding attendance for each price zone.
    + Classification - Classification of concert audience as: Renew, Return, and New
    + Type - Audience type as either a: Subscriber, non-Subscriber
    + Segment - BCG style segmentation: Aficionado, High-value regular, High-value prospect, evolving concert-goer, Committed low-budget, and One-timer
    + Donor Group - The audience's designated donor group per aggregate amounts given in the current FY. Groups are described below:
      
    ***
      1) Group A is <$1,000 donated this FY
      2) Group B is >=$1,000 and <$10,000 donated this FY
      3) Group C is >=$10,000 and <$100,000 donated this FY
      4) Group D is >=$100,000 donated this FY
    ***

***

* The 'Audience Flow' tab provides insight into the number of concerts purchased by customers from the first concert of the fiscal year up through the last concert included in this report. 
    + This excludes all existing subscribers including flex purchasers.
    + This excludes complimentary tickets and therefore only includes paid tickets.
    + We can expect this chart to update on a concert by concert basis.

```{r}
date_of_concert <- date_of_first_concert
```

`r paste(date_of_concert)`
=========================================================================

```{r}
df_summ <- NewDf(df_og)
df_final <- SummarizeDf(df_summ)
df_final <- BindFinalwTotalRow(df_final)
df_final <- DataFormatting(df_final)

df_general <- df_final %>%
  select(Zone,Seats,SubSold,SubAvg,SubRev,SglSold,SglAvg,SglRev,TotSold,PrcntSold,TotRev)
df_comps <- df_final %>%
  select(Zone,Seats,TotComp,PrcntComp)
df_attendance <- df_final %>%
  select(Zone,Seats,Att,CompAtt,SubAtt,SglAtt,TotAtt)

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Revenue Summary

```{r}
df_general %>%
  kable()%>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```


### Comp Data

```{r}
df_comps %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```

### Attendance Data

```{r}
df_attendance %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```


```{r}
concert_date <- date_of_concert

df_renew <- renew_df_creation(df)
df_return <- return_df_creation(df)
df_subscribers <- subs_df_creation(df)
df_this_concert <- this_concert_df_creation(df)
aggregate_df <- aggregate_df_creation(df_for_segmentation)

avg_price <- sum(aggregate_df$tot_paid_amt)/sum(aggregate_df$freq)
upper_quad_price <- avg_price + sd(aggregate_df$avg_paid_amt)
lower_quad_price <- avg_price - sd(aggregate_df$avg_paid_amt)

avg_freq <- mean(aggregate_df$freq)
upper_quad_freq <- avg_freq + sd(aggregate_df$freq)
lower_quad_freq <- ifelse(avg_freq - sd(aggregate_df$freq) <= 0,2.1,avg_freq - sd(aggregate_df$freq))

aggregate_df$segment <- addSegments(aggregate_df,
                                     avg_price,
                                     upper_quad_price,
                                     lower_quad_price,
                                     avg_freq,
                                     upper_quad_freq,
                                     lower_quad_freq)

df_this_concert <- merge(df_this_concert,df_renew,all.x=TRUE)
df_this_concert <- merge(df_this_concert,df_return,all.x=TRUE)
df_this_concert <- merge(df_this_concert,df_subscribers,all.x=TRUE)
df_this_concert <- merge(df_this_concert,df_donor,all.x=TRUE)
df_this_concert <- merge(df_this_concert,aggregate_df[,c('summary_cust_id','segment')],all.x=TRUE)
df_this_concert[is.na(df_this_concert)] <- 0

df_this_concert <- df_this_concert %>%
  mutate(classification = ifelse(renew == 1,'renew',
                                 ifelse(return == 1,'return','new')),
         donor_group = ifelse(gift_plus_pledge < 1000,'Group A',
                              ifelse(gift_plus_pledge < 10000,'Group B',
                                     ifelse(gift_plus_pledge < 100000,'Group C','Group D'))))


```

### Classification
```{r}
plot_classification(df_this_concert)
```

### Purchaser Type
```{r}
plot_type(df_this_concert)
```


### Segment
```{r}
plot_segment(df_this_concert)
```

### Donor Group
```{r}
plot_donor_group(df_this_concert)
```


```{r}
date_of_concert <- date_of_concert + 1
```


`r paste(date_of_concert)`
===============================================

```{r}

df_summ <- NewDf(df_og)
df_final <- SummarizeDf(df_summ)
df_final <- BindFinalwTotalRow(df_final)
df_final <- DataFormatting(df_final)

df_general <- df_final %>%
  select(Zone,Seats,SubSold,SubAvg,SubRev,SglSold,SglAvg,SglRev,TotSold,PrcntSold,TotRev)
df_comps <- df_final %>%
  select(Zone,Seats,TotComp,PrcntComp)
df_attendance <- df_final %>%
  select(Zone,Seats,Att,CompAtt,SubAtt,SglAtt,TotAtt)

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Revenue Summary

```{r}
df_general %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```


### Comp Data

```{r}
df_comps %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```

### Attendance Data

```{r}
df_attendance %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```


```{r}
concert_date <- date_of_concert

df_renew <- renew_df_creation(df)
df_return <- return_df_creation(df)
df_subscribers <- subs_df_creation(df)
df_this_concert <- this_concert_df_creation(df)
aggregate_df <- aggregate_df_creation(df_for_segmentation)

avg_price <- sum(aggregate_df$tot_paid_amt)/sum(aggregate_df$freq)
upper_quad_price <- avg_price + sd(aggregate_df$avg_paid_amt)
lower_quad_price <- avg_price - sd(aggregate_df$avg_paid_amt)

avg_freq <- mean(aggregate_df$freq)
upper_quad_freq <- avg_freq + sd(aggregate_df$freq)
lower_quad_freq <- ifelse(avg_freq - sd(aggregate_df$freq) <= 0,2.1,avg_freq - sd(aggregate_df$freq))

aggregate_df$segment <- addSegments(aggregate_df,
                                     avg_price,
                                     upper_quad_price,
                                     lower_quad_price,
                                     avg_freq,
                                     upper_quad_freq,
                                     lower_quad_freq)

df_this_concert <- merge(df_this_concert,df_renew,all.x=TRUE)
df_this_concert <- merge(df_this_concert,df_return,all.x=TRUE)
df_this_concert <- merge(df_this_concert,df_subscribers,all.x=TRUE)
df_this_concert <- merge(df_this_concert,df_donor,all.x=TRUE)
df_this_concert <- merge(df_this_concert,aggregate_df[,c('summary_cust_id','segment')],all.x=TRUE)
df_this_concert[is.na(df_this_concert)] <- 0

df_this_concert <- df_this_concert %>%
  mutate(classification = ifelse(renew == 1,'renew',
                                 ifelse(return == 1,'return','new')),
         donor_group = ifelse(gift_plus_pledge < 1000,'Group A',
                              ifelse(gift_plus_pledge < 10000,'Group B',
                                     ifelse(gift_plus_pledge < 100000,'Group C','Group D'))))


```

### Classification
```{r}
plot_classification(df_this_concert)
```

### Purchaser Type
```{r}
plot_type(df_this_concert)
```

### Segment
```{r}
plot_segment(df_this_concert)
```

### Donor Group
```{r}
plot_donor_group(df_this_concert)
```


```{r}
date_of_concert <- date_of_concert + 1
```


`r paste(date_of_concert)`
===============================================

```{r}

df_summ <- NewDf(df_og)
df_final <- SummarizeDf(df_summ)
df_final <- BindFinalwTotalRow(df_final)
df_final <- DataFormatting(df_final)

df_general <- df_final %>%
  select(Zone,Seats,SubSold,SubAvg,SubRev,SglSold,SglAvg,SglRev,TotSold,PrcntSold,TotRev)
df_comps <- df_final %>%
  select(Zone,Seats,TotComp,PrcntComp)
df_attendance <- df_final %>%
  select(Zone,Seats,Att,CompAtt,SubAtt,SglAtt,TotAtt)

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Revenue Summary

```{r}
df_general %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```


### Comp Data

```{r}
df_comps %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```

### Attendance Data

```{r}
df_attendance %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```


```{r}
concert_date <- date_of_concert

df_renew <- renew_df_creation(df)
df_return <- return_df_creation(df)
df_subscribers <- subs_df_creation(df)
df_this_concert <- this_concert_df_creation(df)
aggregate_df <- aggregate_df_creation(df_for_segmentation)

avg_price <- sum(aggregate_df$tot_paid_amt)/sum(aggregate_df$freq)
upper_quad_price <- avg_price + sd(aggregate_df$avg_paid_amt)
lower_quad_price <- avg_price - sd(aggregate_df$avg_paid_amt)

avg_freq <- mean(aggregate_df$freq)
upper_quad_freq <- avg_freq + sd(aggregate_df$freq)
lower_quad_freq <- ifelse(avg_freq - sd(aggregate_df$freq) <= 0,2.1,avg_freq - sd(aggregate_df$freq))

aggregate_df$segment <- addSegments(aggregate_df,
                                     avg_price,
                                     upper_quad_price,
                                     lower_quad_price,
                                     avg_freq,
                                     upper_quad_freq,
                                     lower_quad_freq)

df_this_concert <- merge(df_this_concert,df_renew,all.x=TRUE)
df_this_concert <- merge(df_this_concert,df_return,all.x=TRUE)
df_this_concert <- merge(df_this_concert,df_subscribers,all.x=TRUE)
df_this_concert <- merge(df_this_concert,df_donor,all.x=TRUE)
df_this_concert <- merge(df_this_concert,aggregate_df[,c('summary_cust_id','segment')],all.x=TRUE)
df_this_concert[is.na(df_this_concert)] <- 0

df_this_concert <- df_this_concert %>%
  mutate(classification = ifelse(renew == 1,'renew',
                                 ifelse(return == 1,'return','new')),
         donor_group = ifelse(gift_plus_pledge < 1000,'Group A',
                              ifelse(gift_plus_pledge < 10000,'Group B',
                                     ifelse(gift_plus_pledge < 100000,'Group C','Group D'))))


```

### Classification
```{r}
plot_classification(df_this_concert)
```

### Purchaser Type
```{r}
plot_type(df_this_concert)
```

### Segment
```{r}
plot_segment(df_this_concert)
```

### Donor Group
```{r}
plot_donor_group(df_this_concert)
```



Audience Flow
=========================================================================

```{r}
lookup_value <- LookupValue(perf_dts_unique)
df_sub <- SubDf(df_og)
df_flow <- NewDf_CustFlow(df_og,lookup_value,df_sub)
df_unique_perf_spread <- CreateUniquePerfSpread(df_flow)
df_unique_perf_spread <- AddTotalPerfs(df_unique_perf_spread)
total_performances <- AggTotalPerformances(df_unique_perf_spread)
GeneratePlot(total_performances)

```


